# Site settings
title: ayeOS
email: matthew@wetheplural.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Matthew. I like maths, code and music. I also like writing. Here is where I do some writing.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sweetverbs.github.io" # the base hostname & protocol for your site
twitter_username: meanestcreature
github_username: sweetverbs

# Build settings
markdown: redcarpet
markdown_ext: markdown,mkdown,mkdn,mkd,md

highlighting: rouge

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]